site_name: Petalflow
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
        primary: 'white'
        accent: 'green'
  language: en
  
  features:
    - navigation.sections
  features:
    - header.autohide
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/channel/UC-4iINUCd8JtlBh2eVHk0Ig
    - icon: fontawesome/brands/github
      link: https://github.com/petalflow
    - icon: fontawesome/brands/dev
      link: https://dev.to/petalflow
  generator: false

repo_url: https://github.com/petalflow
