site_name: Petalflow
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
        primary: 'white'
        accent: 'green'
  
  features:
    - navigation.sections
  features:
    - header.autohide
    - announce.dismiss
plugins:
  - search:
      lang: pt-br


extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Português
      link: /pt/
      lang: de
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/channel/UC-4iINUCd8JtlBh2eVHk0Ig
    - icon: fontawesome/brands/github
      link: https://github.com/petalflow
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/convutell
  generator: false

repo_url: https://github.com/petalflow
